[package]
name = "backup-manager"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }

clap = { version = "3.1.18", features = ["derive"] }

bytes = "1"
indextree = "4.6.0"
